const query =
  "select PE.EVENTIDENTIFIER,PS.DESCRIPTION,PE.STARTDATETIME ,PE.ENDDATETIME" +
  " from PROMOTIONEVENT PE,PROMOTIONSET PS" +
  " where PE.EVENTIDENTIFIER=PS.EVENTIDENTIFIER" +
  " AND PE.STARTDATETIME >= sysdate -100" +
  " order by PE.STARTDATETIME";

module.exports = query;
